Hw02 unpack string
bambanik/otus-go-hw pull request #3
Opened 2024-02-27 11:15 UTC by bambanik

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-02-27 14:36 UTC, vladislavmass requested changes
Хорошее начало, круто что код проходит все базовые тесты для символов ascii, но решение не проходит тесты для дополнительного задания, а также тесты с многобайтовой кодировкой. Вот список этих тестов
```
{input: "aaф0b", expected: "aab"},
`d\n5abc` - должен вернуть ошибку так как экранировать можно только цифру или обратный слэш
`aaa0b\`- должен вернуть ошибку так как последний слэш ничего не экранирует
```

2024-02-27 14:36 UTC, vladislavmass commented on hw02_unpack_string/unpack_test.go
> +		{input: `d\n5abc`, expected: `d\n\n\n\n\nabc`},
Данный тест кейс должен приводит к ошибке. По условиям задания экранировать в raw строках можно только число или слэш

2024-02-27 14:36 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	for i := 0; i < slen; i++ {
В go очень плохая практика итерироваться по строка, так как индекс адресует не весь символ а только его 1 байт. Поэтому это хорошо работает для однойбатовых кодировок по типу ASCII, но не работает для многобайтовых кодировок

2024-02-27 22:37 UTC, bambanik commented on hw02_unpack_string/unpack_test.go
> +		{input: `d\n5abc`, expected: `d\n\n\n\n\nabc`},
> Данный тест кейс должен приводит к ошибке. По условиям задания экранировать в raw строках можно только число или слэш

Я не менял задание, это взято из [README.md](https://github.com/bambanik/otus-go-hw/blob/hw02_unpack_string/hw02_unpack_string/README.md) :


> Необходимо написать Go функцию, осуществляющую примитивную распаковку строки,
> содержащую повторяющиеся символы/руны, например:
> * "a4bc2d5e" => "aaaabccddddde"
> * "abcd" => "abcd"
> * "3abc" => "" (некорректная строка)
> * "45" => "" (некорректная строка)
> * "aaa10b" => "" (некорректная строка)
> * "aaa0b" => "aab"
> * "" => ""
> * "d\n5abc" => "d\n\n\n\n\nabc"

> {input: `d\n5abc`, expected: `d\n\n\n\n\nabc`},

expected неверный? Должна быть ошибка ErrInvalidString?

2024-02-28 05:38 UTC, vladislavmass commented on hw02_unpack_string/unpack_test.go
> +		{input: `d\n5abc`, expected: `d\n\n\n\n\nabc`},
В Readme и в коде 2 разных тест кейса.  в Readme используются обычные кавычки, которые создают просто строку и для этой строки \n это 1 символ переноса строки, в коде же используются ``` ` ``` кавычки, которые говорят нам что эта строка raw строка или сырая. И в такой строке \n это 2 символа

2024-02-28 12:31 UTC, vladislavmass approved these changes
Хорошая работа, но числа 48 и 92 делает код менее читаемым. Наиболее правильным вариантом было бы создать константы с этим числами и через название указать что это такое

2024-02-28 13:09 UTC, merged